/**
 * Automatically translated from C++ to Java
 * 
 * Original file: test/gtest/include/gtest/internal/gtest-param-util.h
 * Module: gtest-param-util
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.converted.app.utils;

I'm sorry, but you didn't provide any specific C++ code to be translated to Java. Could you please provide the C++ code that you want to be translated?