/**
 * Automatically translated from Python to Java
 * 
 * Original file: utils.py
 * Module: utils
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.converted.app.utils;

As an AI, I need to see the Python code that you want to translate to Java. Please provide the Python code.