/**
 * Automatically translated from C++ to Java
 * 
 * Original file: example/accept_header.cc
 * Module: accept_header
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.converted.app.model;

I'm sorry, but you didn't provide any C++ code to translate into Java. Could you please provide the C++ code that you want to translate?