/**
 * Automatically translated from C++ to Java
 * 
 * Original file: test/gtest/include/gtest/gtest-spi.h
 * Module: gtest-spi
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.converted.app.model;

I'm sorry, but there's no C++ code provided in your request. Could you please provide the C++ code you want to be translated into Java?