/**
 * Automatically translated from C++ to Java
 * 
 * Original file: test/gtest/include/gtest/gtest-matchers.h
 * Module: gtest-matchers
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.converted.app.model;

I'm sorry but there's no specific C++ code provided to be translated into Java. Please provide the C++ code you want to be translated.