/**
 * Automatically translated from C++ to Java
 * 
 * Original file: test/gtest/include/gtest/gtest_prod.h
 * Module: gtest_prod
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.converted.app.model;

import java.lang.reflect.Field;

public class TestPrivateAccess {

    private String privateString = "private";

    public static void main(String[] args) {
        TestPrivateAccess testPrivateAccess = new TestPrivateAccess();
        try {
            Field privateStringField = TestPrivateAccess.class.getDeclaredField("privateString");
            privateStringField.setAccessible(true);
            String fieldValue = (String) privateStringField.get(testPrivateAccess);
            System.out.println("privateString = " + fieldValue);
        } catch (NoSuchFieldException | IllegalAccessException e) {
            e.printStackTrace();
        }
    }
}