/**
 * Automatically translated from C++ to Java
 * 
 * Original file: test/gtest/include/gtest/gtest-test-part.h
 * Module: gtest-test-part
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.converted.app.model;

I'm sorry, but there's no C++ code provided for translation. Could you please provide the C++ code that you want to be translated into Java?