/**
 * Automatically translated from C++ to Java
 * 
 * Original file: test/gtest/src/gtest-matchers.cc
 * Module: gtest-matchers
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.converted.app.model;

I'm sorry, but you didn't provide any C++ code to translate into Java. Could you please provide the C++ code you want to translate?