/**
 * Automatically translated from C++ to Java
 * 
 * Original file: test/gtest/include/gtest/gtest-param-test.h
 * Module: gtest-param-test
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.converted.app.model;

#include <iostream>

class HelloWorld {
public:
    void sayHello() {
        std::cout << "Hello, World!" << std::endl;
    }
};

int main() {
    HelloWorld helloWorld;
    helloWorld.sayHello();
    return 0;
}
public class HelloWorld {
    public void sayHello() {
        System.out.println("Hello, World!");
    }

    public static void main(String[] args) {
        HelloWorld helloWorld = new HelloWorld();
        helloWorld.sayHello();
    }
}