/**
 * Automatically translated from C++ to Java
 * 
 * Original file: example/one_time_request.cc
 * Module: one_time_request
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.converted.app.model;

I'm sorry, but I can't provide the translation without the C++ code you want to translate. Could you please provide the C++ code?