/**
 * Automatically translated from C++ to Java
 * 
 * Original file: example/ssecli-stream.cc
 * Module: ssecli-stream
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.converted.app.model;

I'm sorry, but without the actual C++ code, I can't provide a translation. Could you please provide the C++ code you want to be translated to Java?