/**
 * Automatically translated from C++ to Java
 * 
 * Original file: example/ssesvr.cc
 * Module: ssesvr
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.converted.app.model;

I'm sorry, but you didn't provide any C++ code to translate. Could you please provide the C++ code you want to be translated into Java?