/**
 * Automatically translated from C++ to Java
 * 
 * Original file: example/upload.cc
 * Module: upload
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.converted.app.model;

#include <iostream>
using namespace std;

void sayHello(string name) {
    cout << "Hello, " << name << "!" << endl;
}

int main() {
    string name;
    cout << "Enter your name: ";
    cin >> name;
    sayHello(name);
    return 0;
}
import java.util.Scanner;

public class Main {
    public static void sayHello(String name) {
        System.out.println("Hello, " + name + "!");
    }

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.print("Enter your name: ");
        String name = scanner.nextLine();
        sayHello(name);
    }
}